export type ViewType = 'pawn' | 'cannabis' | 'fireworks'
export type PawnRequestStatus = 'pending' | 'reviewed' | 'quoted' | 'declined' | 'completed'
export type ConditionGrade = 'new' | 'like-new' | 'good' | 'fair' | 'poor'
export type ItemStatus = 'draft' | 'active' | 'reserved' | 'sold' | 'archived'
export type MerchandisingTag = 'just-arrived' | 'rare-find' | 'limited-edition' | 'staff-pick'
export type MoodCategory = 'relax' | 'focus' | 'social' | 'ceremony'
export type ResellerTier = 'bronze' | 'silver' | 'gold'
export type AlertMethod = 'sms' | 'email' | 'none'

export type StaffRole = 'admin' | 'manager' | 'inventory_staff' | 'marketing_staff' | 'customer'

export interface AuthUser {
  uid: string
  email: string | null
  displayName: string | null
  role: StaffRole | null
  isMfaEnrolled: boolean
  isStaff: boolean
  isAdmin: boolean
}

export interface PawnRequest {
  id: string
  uid: string | null
  name: string
  email: string
  phone?: string
  itemDescription: string
  serialNumber?: string
  images: string[]
  status: PawnRequestStatus
  staffNotes?: string
  serialBlacklistHit: boolean
  createdAt: Date
}

// Firestore Timestamps are converted to Date before being assigned here
export interface Item {
  id: string
  title: string
  description: string
  category: string
  viewTag: ViewType
  viewTags?: ViewType[]
  status: ItemStatus
  price: number          // CAD cents (integer)
  condition: ConditionGrade
  images: string[]       // Firebase Storage URLs, watermarked WebP
  videoUrl?: string
  searchTokens: string[] // Prefix tokens — generated by publishItem Cloud Function
  serialNumber?: string
  serialBlacklistFlag?: boolean
  policeHold?: boolean
  holdExpiresAt?: Date
  locationId?: string
  isSeasonalItem?: boolean
  bundleIds?: string[]
  merchandisingTags?: MerchandisingTag[]
  provenanceNotes?: string
  trendingScore?: number
  viewCount?: number
  ebayListingId?: string
  createdAt?: Date
  updatedAt?: Date
  publishedBy?: string
}
